version: '3.8'
services:
  dash:
    container_name: dash-${ENVIRONMENT}
    env_file:
      - ../../.env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dash-net
      - proxy-net
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.${ENVIRONMENT}-dash.rule=Host(`dash.${SUBDOMAIN}${DOMAIN}`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.${ENVIRONMENT}-dash.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.http.routers.${ENVIRONMENT}-dash.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.${ENVIRONMENT}-dash-secured.rule=Host(`dash.${SUBDOMAIN}${DOMAIN}`)" # <== Your Domain Name for the https rule
      - "traefik.http.routers.${ENVIRONMENT}-dash-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.${ENVIRONMENT}-dash-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https


networks:
  dash-net:
    internal: true
    name: dash-net-${ENVIRONMENT}
  proxy-net:
    external:
      name: proxy-net
  common-ext:
    external:
      name: common-ext-${ENVIRONMENT}