PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX afn: <http://jena.apache.org/ARQ/function#>

select distinct
?MonetaryValueId
(afn:localname(?hasCurrency) as ?CurrencyId)
?AmountValue
where {
    {
        select ?MonetaryValueId ?hasCurrency ?AmountValue {
            ?NoticeId a epo:ResultNotice;
                      epo:hasPublicationDate ?NoticePublicationDate;
                      epo:announcesNoticeAwardInformation / epo:hasTotalAwardedValue ?MonetaryValueId.
            values ?NoticePublicationDate {
                $date_range
            }
            ?MonetaryValueId a epo:MonetaryValue;
                             epo:hasCurrency ?hasCurrency;
                             epo:hasAmountValue ?AmountValue.
        }
    } union {
        select ?MonetaryValueId ?hasCurrency ?AmountValue {
            ?NoticeId a epo:ResultNotice;
                      epo:hasPublicationDate ?NoticePublicationDate;
                      epo:refersToProcedure ?ProcedureId.
            values ?NoticePublicationDate {
                $date_range
            }
            ?ProcedureId epo:hasEstimatedValue ?MonetaryValueId .
            ?MonetaryValueId a epo:MonetaryValue;
                             epo:hasCurrency ?hasCurrency;
                             epo:hasAmountValue ?AmountValue.
        }
    } union {
        select ?MonetaryValueId ?hasCurrency ?AmountValue {
            ?NoticeId a epo:ResultNotice;
                      epo:hasPublicationDate ?NoticePublicationDate;
                      epo:refersToLot ?LotId.
            ?LotId epo:hasEstimatedValue ?MonetaryValueId.
            values ?NoticePublicationDate {
                $date_range
            }
            ?MonetaryValueId a epo:MonetaryValue;
                             epo:hasCurrency ?hasCurrency;
                             epo:hasAmountValue ?AmountValue.
        }
    } union {
        select ?MonetaryValueId ?hasCurrency ?AmountValue {
            ?NoticeId a epo:ResultNotice;
                      epo:hasPublicationDate ?NoticePublicationDate;
                      epo:refersToLot ?LotId.
            ?LotId epo:hasRestatedEstimatedValue ?MonetaryValueId.
            values ?NoticePublicationDate {
                $date_range
            }
            ?MonetaryValueId a epo:MonetaryValue;
                             epo:hasCurrency ?hasCurrency;
                             epo:hasAmountValue ?AmountValue.
        }
    } union {
        select ?MonetaryValueId ?hasCurrency ?AmountValue {
            ?NoticeId a epo:ResultNotice;
                      epo:hasPublicationDate ?NoticePublicationDate;
                      epo:refersToLot ?LotId.
            ?LotId epo:hasRestatedEstimatedValue ?MonetaryValueId.
            ?LotAwardOutcomeId epo:describesLot ?LotId;
                               a epo:LotAwardOutcome;
                               epo:hasAwardedValue ?MonetaryValueId.
            values ?NoticePublicationDate {
                $date_range
            }
            ?MonetaryValueId a epo:MonetaryValue;
                             epo:hasCurrency ?hasCurrency;
                             epo:hasAmountValue ?AmountValue.
        }
    } union {
        select ?MonetaryValueId ?hasCurrency ?AmountValue {
            ?NoticeId a epo:ResultNotice;
                      epo:hasPublicationDate ?NoticePublicationDate;
                      epo:refersToLot ?LotId.
            ?LotId epo:hasRestatedEstimatedValue ?MonetaryValueId.
            ?LotAwardOutcomeId epo:describesLot ?LotId;
                               a epo:LotAwardOutcome;
                               epo:hasBargainPrice ?MonetaryValueId.
            values ?NoticePublicationDate {
                $date_range
            }
            ?MonetaryValueId a epo:MonetaryValue;
                             epo:hasCurrency ?hasCurrency;
                             epo:hasAmountValue ?AmountValue.
        }
    } union {
        select ?MonetaryValueId ?hasCurrency ?AmountValue {
            ?NoticeId a epo:ResultNotice;
                      epo:hasPublicationDate ?NoticePublicationDate;
                      epo:refersToLot ?LotId.
            ?LotId epo:hasRestatedEstimatedValue ?MonetaryValueId.
            ?LotAwardOutcomeId epo:describesLot ?LotId;
                               epo:hasBargainPrice ?MonetaryValueId.
            ?SubmissionStatisticalInformationId epo:summarisesInformationForLotAwardOutcome ?LotAwardOutcomeId;
                                            a epo:SubmissionStatisticalInformation;
                                            epo:hasHighestReceivedTenderValue ?MonetaryValueId.
            values ?NoticePublicationDate {
                $date_range
            }
            ?MonetaryValueId a epo:MonetaryValue;
                             epo:hasCurrency ?hasCurrency;
                             epo:hasAmountValue ?AmountValue.
        }
    } union {
        select ?MonetaryValueId ?hasCurrency ?AmountValue {
            ?NoticeId a epo:ResultNotice;
                      epo:hasPublicationDate ?NoticePublicationDate;
                      epo:refersToLot ?LotId.
            ?LotId epo:hasRestatedEstimatedValue ?MonetaryValueId.
            ?LotAwardOutcomeId epo:describesLot ?LotId;
                               epo:hasBargainPrice ?MonetaryValueId.
            ?SubmissionStatisticalInformationId epo:summarisesInformationForLotAwardOutcome ?LotAwardOutcomeId;
                                            a epo:SubmissionStatisticalInformation;
                                            epo:hasLowestReceivedTenderValue ?MonetaryValueId.
            values ?NoticePublicationDate {
                $date_range
            }
            ?MonetaryValueId a epo:MonetaryValue;
                             epo:hasCurrency ?hasCurrency;
                             epo:hasAmountValue ?AmountValue.
        }
    }
}