PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX afn: <http://jena.apache.org/ARQ/function#>
PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX dcterms: <http://purl.org/dc/terms/>

select distinct
(afn:localname(?Address) as ?AddressId)
(afn:localname(?hasCountryCode) as ?CountryCode)
(afn:localname(?hasNUTSId) as ?NUTSId)
?PostCode
?PostName
?Thoroughfare
where {
    ?NoticeId a epo:ResultNotice;
              epo:hasPublicationDate ?NoticePublicationDate;
              epo:refersToProcedure ?ProcedureId.
    values ?NoticePublicationDate {
        $date_range
    }

    ?NoticeId epo:announcesRole ?Role .
    {
        ?Role a epo:Buyer.
    } union {
        ?Role a epo:Winner.
    }
    ?Role epo:playedBy ?Organization.
    ?Organization cccev:registeredAddress ?Address.
    ?Address a locn:Address.

    optional {
        ?Address epo:hasCountryCode ?hasCountryCode .
    }
    optional {
        ?Address epo:hasNutsCode ?hasNUTSId.
    }
    optional {
        ?Address locn:postCode ?PostCode.
    }
    optional {
        ?Address locn:postName ?PostName.
    }
    optional {
        ?Address locn:thoroughfare ?Thoroughfare.
    }
}