PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX afn: <http://jena.apache.org/ARQ/function#>
PREFIX cpov: <http://data.europa.eu/m8g/>
PREFIX org: <http://www.w3.org/ns/org#>

select distinct
(concat(str(afn:localname(?Procedure)), str(afn:localname(?Organization))) as ?ProcedureOrganizationId)
(afn:localname(?Procedure) as ?ProcedureId)
(afn:localname(?Organization) as ?OrganizationId)
(afn:localname(?ContactPoint) as ?ContactPointId)
where {
    ?NoticeId a epo:ResultNotice;
                   epo:hasPublicationDate ?NoticePublicationDate;
                   epo:refersToProcedure ?Procedure;
				   epo:announcesRole ?BuyerId.

    values ?NoticePublicationDate {
       $date_range
    }

    ?BuyerId a epo:Buyer;
             epo:hasContactPointInRole ?ContactPoint;
             epo:playedBy ?Organization.
	?ContactPoint a cpov:ContactPoint.
}