PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX afn: <http://jena.apache.org/ARQ/function#>

select distinct
(concat(str(afn:localname(?Lot)), ?LotCPV) as ?LotCPVId)
(afn:localname(?Lot) as ?LotId)
?OriginalCPV
where {
    ?NoticeId a epo:ResultNotice;
              epo:hasPublicationDate ?NoticePublicationDate;
              epo:refersToLot ?Lot.

    values ?NoticePublicationDate {
        $date_range
    }

    ?Lot a epo:Lot;
           epo:hasPurpose / epo:hasAdditionalClassification ?LotSpecificCPVURI.
	bind(afn:localname(?LotSpecificCPVURI) as ?OriginalCPV)
}