PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX afn: <http://jena.apache.org/ARQ/function#>

select distinct
?NoticeId
?NoticePublicationDate
?ProcedureId
?TotalAwardedValue
(afn:localname(?TotalAwardedValueCurrencyURI) as ?TotalAwardedValueCurrency)
where {
    ?NoticeId a epo:ResultNotice;
                   epo:hasPublicationDate ?NoticePublicationDate;
                   epo:refersToProcedure ?ProcedureId.

    values ?NoticePublicationDate {
        $date_range
    }

    optional {
    	?NoticeId epo:announcesNoticeAwardInformation / epo:hasTotalAwardedValue ?MonetaryValue.
        ?MonetaryValue a epo:MonetaryValue;
                       epo:hasAmountValue ?TotalAwardedValue;
                       epo:hasCurrency ?TotalAwardedValueCurrencyURI.
    }
}