PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX afn: <http://jena.apache.org/ARQ/function#>

select distinct
(afn:localname(?SubmissionStatisticalInformation) as ?SubmissionStatisticalInformationId)
?hasReceivedSMETenders
?hasReceivedTenders
?HighestReceivedTenderValue
(afn:localname(?HighestReceivedTenderValueCurrencyURI) as ?HighestReceivedTenderValueCurrency)
?LowestReceivedTenderValue
(afn:localname(?LowestReceivedTenderValueCurrencyURI) as ?LowestReceivedTenderValueCurrency)
?hasEUReceivedTenders
?hasReceivedNonEUTenders
?hasElectronicTenders
(afn:localname(?LotAwardOutcome) as ?LotAwardOutcomeId)
where {
    ?NoticeId a epo:ResultNotice;
              epo:hasPublicationDate ?NoticePublicationDate;
              epo:refersToLot ?LotId.

    values ?NoticePublicationDate {
        $date_range
    }

    ?LotId a epo:Lot.
    ?LotAwardOutcome epo:describesLot ?LotId;
                       a epo:LotAwardOutcome.
    ?SubmissionStatisticalInformation epo:summarisesInformationForLotAwardOutcome ?LotAwardOutcome;
                                        a epo:SubmissionStatisticalInformation.

    optional {
        ?SubmissionStatisticalInformation epo:hasReceivedSMETenders ?hasReceivedSMETenders .
    }
    optional {
        ?SubmissionStatisticalInformation epo:hasReceivedTenders ?hasReceivedTenders .
    }
    optional {
        ?SubmissionStatisticalInformation epo:hasHighestReceivedTenderValue ?HighestReceivedTenderMonetaryValue .
        ?HighestReceivedTenderMonetaryValue a epo:MonetaryValue;
                                            epo:hasAmountValue ?HighestReceivedTenderValue;
                                            epo:hasCurrency ?HighestReceivedTenderValueCurrencyURI.

    }
    optional {
        ?SubmissionStatisticalInformation epo:hasLowestReceivedTenderValue ?LowestReceivedTenderMonetaryValue .
        ?LowestReceivedTenderMonetaryValue a epo:MonetaryValue;
                                            epo:hasAmountValue ?LowestReceivedTenderValue;
                                            epo:hasCurrency ?LowestReceivedTenderValueCurrencyURI.
    }
    optional {
        ?SubmissionStatisticalInformation epo:hasEUReceivedTenders ?hasEUReceivedTenders .
    }
    optional {
        ?SubmissionStatisticalInformation epo:hasElectronicTenders ?hasElectronicTenders .
    }
    optional {
        ?SubmissionStatisticalInformation epo:hasReceivedNonEUTenders ?hasReceivedNonEUTenders .
    }
}