PREFIX epo: <http://data.europa.eu/a4g/ontology#>

select distinct
?WinnerId
?OrganizationId
where {
    ?NoticeId a epo:ResultNotice;
              epo:hasPublicationDate ?NoticePublicationDate;
              epo:announcesRole ?WinnerId.

    values ?NoticePublicationDate {
        $date_range
    }

    ?WinnerId a epo:Winner;
              epo:playedBy ?OrganizationId.
}