PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX cpov: <http://data.europa.eu/m8g/>
PREFIX afn: <http://jena.apache.org/ARQ/function#>

select distinct
(concat(str(afn:localname(?LotAwardOutcome)), str(afn:localname(?Organization))) as ?LotAwardOutcomeOrganizationId)
(afn:localname(?LotAwardOutcome) as ?LotAwardOutcomeId)
(afn:localname(?Organization) as ?OrganizationId)
(afn:localname(?ContactPoint) as ?ContactPointId)
where {
    ?NoticeId a epo:ResultNotice;
              epo:hasPublicationDate ?NoticePublicationDate;
              epo:refersToLot ?LotId;
              epo:announcesRole ?WinnerId.

    values ?NoticePublicationDate {
        $date_range
    }

    ?LotId a epo:Lot.
    ?LotAwardOutcome epo:describesLot ?LotId;
                       a epo:LotAwardOutcome;
                       epo:comprisesTenderAwardOutcome ?Tender.
    ?Tender epo:indicatesAwardOfLotToWinner ?WinnerId.
    ?WinnerId a epo:Winner;
              epo:playedBy ?Organization.
    ?Organization epo:hasPrimaryContactPoint ?ContactPoint .
    ?ContactPoint a cpov:ContactPoint.
}